<h2>Editar tarea</h2>
<form action="<?php echo ENLACE_APLICACION . "tarea/editar"; ?>" method="POST">
    <input type="hidden" name="id" class="form-control" value="<?php echo $this->tarea["id"]; ?>">
    <label for="nombre">Nombre</label>
    <input type="text" name="nombre" value="<?php echo $this->tarea["nombre"]; ?>">
    <label for="descripcion">Descripción</label>
    <textarea name="descripcion"><?php echo $this->tarea["descripcion"]; ?></textarea>
    <label for="fecha">Fecha</label>
    <input type="date" name="fecha" value="<?php echo $this->tarea["fecha"]; ?>">
    <label for="prioridad">Prioridad</label>
    <input type="range" name="prioridad" min="0" max="10" value="<?php echo $this->tarea["prioridad"]; ?>">
    <label for="categoria">Categoría</label>
    <select name="categoria_id">
    <?php foreach ($this->categorias as $categoria) { ?>
    <option value="<?php echo $categoria["id"]; ?>" <?php if ($categoria["id"] == $this->tarea["categoria_id"]) echo 'selected="selected"'; ?>>
    <?php echo $categoria["nombre"]; ?>
    </option>
    <?php } ?>
    </select>
    <input type="submit">
</form>