<h2>Lista de tareas</h2>
<a href="<?php echo ENLACE_APLICACION . "tarea/crear"; ?>">Crear tarea</a>
<table border="1">
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Fecha</th>
        <th>Prioridad</th>
        <th>Acción</th>
    </tr>
    <?php foreach ($this->tareas as $tarea) { ?>
    <tr>
        <td><?php echo $tarea["id"]; ?></td>
        <td><?php echo $tarea["nombre"]; ?></td>        
        <td><?php echo $tarea["descripcion"]; ?></td>
        <td><?php echo $tarea["fecha"]; ?></td>
        <td><?php echo $tarea["prioridad"]; ?></td>
        <td><a href="<?php echo ENLACE_APLICACION . "tarea/editar/" . $tarea["id"]; ?>">Editar</a> | <a href="<?php echo ENLACE_APLICACION . "tarea/borrar/" . $tarea["id"]; ?>">Eliminar</a></td>
    </tr>
    <?php } ?>
</table>